// Keeps <head> correct during client-side navigation.
//
// The static shells generated by scripts/generate-html.mjs already carry the
// right tags for whichever URL the user landed on. This hook covers what happens
// after that: react-router swaps the view without a document load, so the head
// would otherwise keep describing the landing page forever.
//
// No new dependency (deliberately not react-helmet) — this is ~40 lines of DOM.

import { useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import { getRouteMeta, canonicalFor, SITE_NAME, OG_IMAGE, OG_IMAGE_ALT } from './routes.js';
import { schemaFor } from './schema.js';

// Upsert <meta>, keyed by name= or property= depending on the tag family.
function setMeta(attr, key, content) {
  let el = document.head.querySelector(`meta[${attr}="${key}"]`);
  if (!el) {
    el = document.createElement('meta');
    el.setAttribute(attr, key);
    document.head.appendChild(el);
  }
  el.setAttribute('content', content);
}

function setCanonical(href) {
  let el = document.head.querySelector('link[rel="canonical"]');
  if (!el) {
    el = document.createElement('link');
    el.setAttribute('rel', 'canonical');
    document.head.appendChild(el);
  }
  el.setAttribute('href', href);
}

function setSchema(pathname) {
  let el = document.head.querySelector('script[type="application/ld+json"]');
  if (!el) {
    el = document.createElement('script');
    el.setAttribute('type', 'application/ld+json');
    document.head.appendChild(el);
  }
  el.textContent = JSON.stringify(schemaFor(pathname));
}

export default function useSeo() {
  const { pathname } = useLocation();

  useEffect(() => {
    const meta = getRouteMeta(pathname);
    const url = canonicalFor(pathname);

    document.title = meta.title;
    setMeta('name', 'description', meta.description);
    setCanonical(url);

    // noindex pages still get "follow" so link equity passes through them.
    setMeta('name', 'robots', meta.index ? 'index, follow' : 'noindex, follow');

    setMeta('property', 'og:title', meta.title);
    setMeta('property', 'og:description', meta.description);
    setMeta('property', 'og:url', url);
    setMeta('property', 'og:type', 'website');
    setMeta('property', 'og:site_name', SITE_NAME);
    setMeta('property', 'og:image', OG_IMAGE);
    setMeta('property', 'og:image:alt', OG_IMAGE_ALT);

    setMeta('name', 'twitter:card', 'summary_large_image');
    setMeta('name', 'twitter:title', meta.title);
    setMeta('name', 'twitter:description', meta.description);
    setMeta('name', 'twitter:image', OG_IMAGE);

    setSchema(pathname);
  }, [pathname]);
}
